function [dR, M, nabla_M, nabla_mu, div_nabla_R, J] = ...
            ch_shape(domain, integration_point, global_basis_index, ...
            element_local_mapping, element_ranges, element)
        
        switch domain.rank
            
            case 1
                [dR, M, nabla_M, nabla_mu, div_nabla_R, J] = ...
            ch_shape_1d(domain, integration_point, global_basis_index, ...
            element_local_mapping, element_ranges, element);
            
            case 2
                [dR, M, nabla_M, nabla_mu, div_nabla_R, J] = ...
            ch_shape_2d(domain, integration_point, global_basis_index, ...
            element_local_mapping, element_ranges, element);
            
            case 3
                [dR, M, nabla_M, nabla_mu, div_nabla_R, J] = ...
            ch_shape_3d(domain, integration_point, global_basis_index, ...
            element_local_mapping, element_ranges, element);
           
            otherwise
                error('Domain rank is invalid. Can only give shape functions for domains of rank 1, 2 or 3.');
        end
end