function [R, dR, J] = FastShape(GeometryObject,IntegrationPoint, ...
    global_basis_index,element_local_mapping,element_ranges,element)
    switch GeometryObject.rank
        case 1
            [R, dR, J] = FastShape1D(GeometryObject,IntegrationPoint, ...
                global_basis_index,element_local_mapping,element_ranges,...
                element) ;
        case 2
            [R, dR, J] = FastShape2D(GeometryObject,IntegrationPoint, ... 
                global_basis_index, element_local_mapping, element_ranges, ...
                element);
        case 3
            [R, dR, J] = FastShape3D(GeometryObject,IntegrationPoint, ... 
                global_basis_index, element_local_mapping, element_ranges, ...
                element);
    end
end