function [R, dR, d2R, J] = FastSecondShape(GeometryObject, IntegrationPoint, ...
    global_basis_index, element_local_mapping, element_ranges, element)
    switch GeometryObject.rank
        case 1
            [R, dR, d2R, J] = FastSecondShape1D(GeometryObject,IntegrationPoint, ...
                global_basis_index,element_local_mapping,element_ranges,...
                element);
        case 2
            [R, dR, d2R, J] = FastSecondShape2D(GeometryObject,IntegrationPoint, ...
                global_basis_index,element_local_mapping,element_ranges,...
                element);
        case 3
            [R, dR, d2R, J] = FastSecondShape3D(GeometryObject,IntegrationPoint, ...
                global_basis_index,element_local_mapping,element_ranges,...
                element);